# Generated by Django 4.1.7 on 2023-04-19 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0008_remove_menu_dia1_remove_menu_dia2_remove_menu_dia3_and_more"),
        ("pedidos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedido",
            name="id_menu",
        ),
        migrations.CreateModel(
            name="Pedido_Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="menus.menu"
                    ),
                ),
                (
                    "id_pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pedidos.pedido"
                    ),
                ),
            ],
        ),
    ]
